// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"w-full py-6 border-b border-stone-200 bg-white/80 backdrop-blur-md sticky top-0 z-50\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between\"><div class=\"flex items-center gap-2\"><div class=\"w-8 h-8 bg-stone-900 rounded-sm flex items-center justify-center text-white font-serif italic text-xl\">B</div><h1 class=\"font-serif text-2xl tracking-tight text-stone-900 font-semibold\">Lumina <span class=\"text-stone-400 font-light italic\">Books</span></h1></div><div class=\"flex items-center gap-8 font-sans text-sm uppercase tracking-widest text-stone-600\"><a href=\"/\" class=\"hover:text-stone-900 transition-colors border-b border-transparent hover:border-stone-900 pb-1\">Collection</a> <a href=\"#\" class=\"hover:text-stone-900 transition-colors border-b border-transparent hover:border-stone-900 pb-1\">Categories</a> <a href=\"#\" class=\"hover:text-stone-900 transition-colors border-b border-transparent hover:border-stone-900 pb-1\">About</a> <a href=\"/\" class=\"group relative\"><span class=\"sr-only\">Home</span> <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"text-stone-500 group-hover:text-stone-900 transition-colors\"><path d=\"m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"></path><polyline points=\"9 22 9 12 15 12 15 22\"></polyline></svg></a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
